// <auto-generated />
using System;
using Infraestructura.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240507034406_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("87b03b8c-50c6-4fea-93d4-ed58ad21b3e3"),
                            Category = 1,
                            Descripcion = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_818355-MLU74163648935_012024-F.webp",
                            Name = "Lavadora de carga frontal",
                            Price = 579999m
                        },
                        new
                        {
                            ProductId = new Guid("5907afbd-5a19-4e5c-ac20-e1ab0f23cf1e"),
                            Category = 1,
                            Descripcion = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 61,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745773-MLA47575105862_092021-O.webp",
                            Name = "Licuadora de alta potencia",
                            Price = 42500m
                        },
                        new
                        {
                            ProductId = new Guid("c39ca82b-e3a8-43b9-b1b7-73d4f646e878"),
                            Category = 1,
                            Descripcion = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700777-MLU75436781292_042024-O.webp",
                            Name = "Horno eléctrico de convección",
                            Price = 169999m
                        },
                        new
                        {
                            ProductId = new Guid("c781e7e5-26d1-4480-83f6-d37c4fad0a35"),
                            Category = 1,
                            Descripcion = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 43,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678901-MLU75358482641_032024-O.webp",
                            Name = "Aspiradora robotizada",
                            Price = 70705m
                        },
                        new
                        {
                            ProductId = new Guid("ea5a79ee-9723-40d4-915a-1696b7c70a82"),
                            Category = 2,
                            Descripcion = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816025-MLU72748491987_112023-O.webp",
                            Name = "Smartphone de última generación",
                            Price = 1900000m
                        },
                        new
                        {
                            ProductId = new Guid("ff9ff8f2-4b44-4737-b321-d9e93f1e5e5e"),
                            Category = 2,
                            Descripcion = "Inflador De Neumáticos Portátil X8",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_667807-MLU72649504918_112023-O.webp",
                            Name = "Inflador Portátil ultraligero",
                            Price = 400000m
                        },
                        new
                        {
                            ProductId = new Guid("2950c60f-31a9-4f66-aadb-4db4fd006158"),
                            Category = 2,
                            Descripcion = "Camara Digital Mirrorless Sony Alpha A6100 4k Wifi Sel1650.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_659460-MLU72646998907_112023-O.webp",
                            Name = "Cámara digital réflex Sony",
                            Price = 1069000m
                        },
                        new
                        {
                            ProductId = new Guid("58d14fb5-5cba-447e-8f74-83f3e5f5f06b"),
                            Category = 2,
                            Descripcion = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_796079-MLU75556122361_042024-F.webp",
                            Name = "Smart TV de 55 pulgadas",
                            Price = 734999m
                        },
                        new
                        {
                            ProductId = new Guid("b5fca9e7-4ffd-4bc4-be4e-94ea30b39e72"),
                            Category = 2,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_938092-MLA45480677826_042021-O.webp",
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("2d4907ea-2384-4219-aaa0-45b756b5d682"),
                            Category = 2,
                            Descripcion = "Sony PlayStation 5 825GB God of War Ragnarok Bundle color blanco y negro.",
                            Discount = 11,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700033-MLA69689802995_052023-O.webp",
                            Name = "Sony Playstation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("870cb16e-68c2-4616-80ee-281b8ca8e463"),
                            Category = 3,
                            Descripcion = "Acolchado edredón 2 plazas y 1/2 (2 plazas y media) liso reversible Abrigado invierno.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_748192-MLA53582903699_022023-O.webp",
                            Name = "Acolchados Lisos 2 1/2 Plazas Reversible",
                            Price = 31243m
                        },
                        new
                        {
                            ProductId = new Guid("8a2b0893-57fc-438f-94ae-97155e721a7d"),
                            Category = 3,
                            Descripcion = "Cartera Cuero Genuino Reptil Bolso Mochila Mujer Cierre.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_869901-MLA54619063288_032023-F.webp",
                            Name = "Bolso de cuero genuino",
                            Price = 95000m
                        },
                        new
                        {
                            ProductId = new Guid("cc4bdfff-c059-4caf-9130-ed04b4bdc8a1"),
                            Category = 3,
                            Descripcion = "Anteojos de sol polarizados Vulk Reporter en color sblk/s10.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_604456-MLA48170692330_112021-O.webp",
                            Name = "Lente De Sol Vulk",
                            Price = 64800m
                        },
                        new
                        {
                            ProductId = new Guid("a372f968-6ddd-47b4-a321-fc2a172d5ea6"),
                            Category = 3,
                            Descripcion = "Smartwatch Reloj Inteligente Dt N0.1 Dt3 Mate Doble Malla.",
                            Discount = 13,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_748519-MLA72356877039_102023-F.webp",
                            Name = "Reloj inteligente elegante",
                            Price = 75950m
                        },
                        new
                        {
                            ProductId = new Guid("2db9b3de-41cb-4f16-a292-10e2161b1f76"),
                            Category = 3,
                            Descripcion = "Zapatillas Puma Caven 2.0 Blanca",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_994477-MLA74957384571_032024-O.webp",
                            Name = "Zapatillas deportivas de moda",
                            Price = 84999m
                        },
                        new
                        {
                            ProductId = new Guid("d93aa009-94d3-4db0-96d7-cd44a7da5b32"),
                            Category = 4,
                            Descripcion = "Juego De Sabanas Queen 400hilos 100% Algodon.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829765-MLA73477087898_122023-O.webp",
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 85265m
                        },
                        new
                        {
                            ProductId = new Guid("ec154df9-3ac1-43b0-9444-c11fd177150c"),
                            Category = 4,
                            Descripcion = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814774-MLA73709732208_012024-O.webp",
                            Name = "Jarrón de cerámica artesanal",
                            Price = 27550m
                        },
                        new
                        {
                            ProductId = new Guid("0f36b6ce-219e-4988-a648-f529a5ed935c"),
                            Category = 4,
                            Descripcion = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_929599-MLA54852993202_042023-F.webp",
                            Name = "Lámpara de pie moderna",
                            Price = 85050m
                        },
                        new
                        {
                            ProductId = new Guid("c96134dd-71f1-490b-86f3-d98142b074c4"),
                            Category = 4,
                            Descripcion = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 35983m
                        },
                        new
                        {
                            ProductId = new Guid("2be8a358-68c8-4e0b-b125-251caa4a0718"),
                            Category = 5,
                            Descripcion = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 28,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Set de maquillaje profesional",
                            Price = 39528m
                        },
                        new
                        {
                            ProductId = new Guid("621d1be7-b8b0-493b-980c-7af55bd852e5"),
                            Category = 5,
                            Descripcion = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_870569-MLA74827280389_022024-O.webp",
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 36827m
                        },
                        new
                        {
                            ProductId = new Guid("f0f7cf7b-4603-4262-b198-4d0ceb4d154e"),
                            Category = 5,
                            Descripcion = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918096-MLA74134687068_012024-O.webp",
                            Name = "Serum facial rejuvenecedor",
                            Price = 18290m
                        },
                        new
                        {
                            ProductId = new Guid("ee6d142b-557f-441a-acce-dd6cbd80a201"),
                            Category = 5,
                            Descripcion = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 24,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_999356-MLU74959566341_032024-O.webp",
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 92369m
                        },
                        new
                        {
                            ProductId = new Guid("c5517268-bf05-4827-b838-8646e4e22445"),
                            Category = 5,
                            Descripcion = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 60,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_864195-MLU75358350003_032024-F.webp",
                            Name = "Kit de manicura y pedicura",
                            Price = 4799m
                        },
                        new
                        {
                            ProductId = new Guid("edef87a4-abaa-417c-a838-07bab0655cb3"),
                            Category = 6,
                            Descripcion = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_819576-MLU75591901591_042024-F.webp",
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 283226m
                        },
                        new
                        {
                            ProductId = new Guid("f18bb132-6862-4de8-af5c-1a0ed04dc587"),
                            Category = 6,
                            Descripcion = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_853020-MLU74646955786_022024-F.webp",
                            Name = "Tienda de campaña para 4 personas",
                            Price = 150000m
                        },
                        new
                        {
                            ProductId = new Guid("2bfb0b83-552e-41cb-b095-c57a58fe296e"),
                            Category = 6,
                            Descripcion = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_674284-MLU74132469460_012024-F.webp",
                            Name = "Raquetas de tenis de alta gama",
                            Price = 246900m
                        },
                        new
                        {
                            ProductId = new Guid("4a6c87eb-1902-4f2b-a0eb-2bd7d1791985"),
                            Category = 6,
                            Descripcion = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_981675-MLU75436946294_042024-O.webp",
                            Name = "Balón de fútbol oficial",
                            Price = 62200m
                        },
                        new
                        {
                            ProductId = new Guid("045277c5-7864-4f7a-b288-6216bf3c9dc7"),
                            Category = 7,
                            Descripcion = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_688616-MLA70719693003_072023-O.webp",
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 59900m
                        },
                        new
                        {
                            ProductId = new Guid("a04f70af-ab13-4513-83da-b16f05cf621d"),
                            Category = 7,
                            Descripcion = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_825422-MLA48732174078_012022-O.webp",
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 47491m
                        },
                        new
                        {
                            ProductId = new Guid("2d673e79-3991-4a55-80d1-f4bd3988cef6"),
                            Category = 7,
                            Descripcion = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_681463-MLU72607866767_102023-O.webp",
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 29989m
                        },
                        new
                        {
                            ProductId = new Guid("62dd17f4-2b66-4cf3-ae05-6f54de7cef78"),
                            Category = 7,
                            Descripcion = "Juego de mesa estratégico con tablero plegable y fichas de madera.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_818301-MLU72732448659_112023-O.webp",
                            Name = "Juego de mesa de Ajedrez",
                            Price = 34400m
                        },
                        new
                        {
                            ProductId = new Guid("fed20ea0-c05c-40a3-9eac-fd8fe660fef7"),
                            Category = 8,
                            Descripcion = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_756320-MLU70634026054_072023-F.webp",
                            Name = "Caja de vinos seleccionados",
                            Price = 187800m
                        },
                        new
                        {
                            ProductId = new Guid("e468b6d7-d9b9-4b14-ac9f-a2b90fb07f31"),
                            Category = 8,
                            Descripcion = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 17,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_890748-MLA73914321216_012024-O.webp",
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 29682m
                        },
                        new
                        {
                            ProductId = new Guid("99e6f4ab-d849-4d57-9435-82b4aed8146f"),
                            Category = 8,
                            Descripcion = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745130-MLA51091920365_082022-O.webp",
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 4360m
                        },
                        new
                        {
                            ProductId = new Guid("194cb7f0-cc75-4bc7-ae4a-dabf348a62a0"),
                            Category = 8,
                            Descripcion = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_773299-MLU72576428368_112023-O.webp",
                            Name = "Cafetera espresso automática",
                            Price = 241590m
                        },
                        new
                        {
                            ProductId = new Guid("6bdd82b3-e90d-4023-9364-d4619f98f5fa"),
                            Category = 9,
                            Descripcion = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_737839-MLA52392671527_112022-O.webp",
                            Name = "Bestseller del New York Times",
                            Price = 15822m
                        },
                        new
                        {
                            ProductId = new Guid("3b056c7d-ead4-4513-8ee8-cb6e5fcb812a"),
                            Category = 9,
                            Descripcion = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_869243-MLU74994926858_032024-O.webp",
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 17000m
                        },
                        new
                        {
                            ProductId = new Guid("cc872229-0c18-47db-842f-50d65ba3ab88"),
                            Category = 9,
                            Descripcion = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_789389-MLA42259351508_062020-O.webp",
                            Name = "Atlas geográfico interactivo",
                            Price = 16980m
                        },
                        new
                        {
                            ProductId = new Guid("4a49dc52-7c1c-4835-8544-72eec788d8cc"),
                            Category = 9,
                            Descripcion = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_924058-MLA50987231299_082022-F.webp",
                            Name = "Kit de experimentos científicos para niños",
                            Price = 27900m
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCardId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "category")
                        .WithMany("Product")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", "Product")
                        .WithMany("product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", "sale")
                        .WithMany("SaleProduct")
                        .HasForeignKey("SaleId");

                    b.Navigation("Product");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
