// <auto-generated />
using System;
using Infraestructura.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("4d9f7a50-68c0-40d0-a72c-bb9cd99f1887"),
                            Category = 1,
                            Description = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_818355-MLU74163648935_012024-F.webp",
                            Name = "Lavadora de carga frontal",
                            Price = 579999m
                        },
                        new
                        {
                            ProductId = new Guid("96704d21-f755-4c6e-8082-1835b5cdbfb3"),
                            Category = 1,
                            Description = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 61,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745773-MLA47575105862_092021-O.webp",
                            Name = "Licuadora de alta potencia",
                            Price = 42500m
                        },
                        new
                        {
                            ProductId = new Guid("19817a03-b49a-48b4-9d68-ff0fac5bd8b2"),
                            Category = 1,
                            Description = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700777-MLU75436781292_042024-O.webp",
                            Name = "Horno eléctrico de convección",
                            Price = 169999m
                        },
                        new
                        {
                            ProductId = new Guid("c2e2f591-e363-4382-ae7a-d9645664a26e"),
                            Category = 1,
                            Description = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 43,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678901-MLU75358482641_032024-O.webp",
                            Name = "Aspiradora robotizada",
                            Price = 70705m
                        },
                        new
                        {
                            ProductId = new Guid("8c1c3701-0780-482b-a1c8-307797746b6b"),
                            Category = 2,
                            Description = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816025-MLU72748491987_112023-O.webp",
                            Name = "Smartphone de última generación",
                            Price = 1900000m
                        },
                        new
                        {
                            ProductId = new Guid("f4852e57-2935-4aa5-ad4f-222a310bfdfc"),
                            Category = 2,
                            Description = "Inflador De Neumáticos Portátil X8",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_667807-MLU72649504918_112023-O.webp",
                            Name = "Inflador Portátil ultraligero",
                            Price = 400000m
                        },
                        new
                        {
                            ProductId = new Guid("6d9b5690-9a3b-4f72-9aab-375f49f71e8f"),
                            Category = 2,
                            Description = "Camara Digital Mirrorless Sony Alpha A6100 4k Wifi Sel1650.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_659460-MLU72646998907_112023-O.webp",
                            Name = "Cámara digital réflex Sony",
                            Price = 1069000m
                        },
                        new
                        {
                            ProductId = new Guid("1eaf09c6-ce84-4f6f-825e-fdcf70e7ebf0"),
                            Category = 2,
                            Description = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_796079-MLU75556122361_042024-F.webp",
                            Name = "Smart TV de 55 pulgadas",
                            Price = 734999m
                        },
                        new
                        {
                            ProductId = new Guid("0d18242c-9b24-42a4-9d71-9ffa3e8c958f"),
                            Category = 2,
                            Description = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_938092-MLA45480677826_042021-O.webp",
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("e1e6fc9e-5d92-4a26-94ae-ef1af3af5d27"),
                            Category = 2,
                            Description = "Sony PlayStation 5 825GB God of War Ragnarok Bundle color blanco y negro.",
                            Discount = 11,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700033-MLA69689802995_052023-O.webp",
                            Name = "Sony Playstation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("2b12f33c-a11f-4692-8f1c-2f6800394b7a"),
                            Category = 3,
                            Description = "Acolchado edredón 2 plazas y 1/2 (2 plazas y media) liso reversible Abrigado invierno.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_748192-MLA53582903699_022023-O.webp",
                            Name = "Acolchados Lisos 2 1/2 Plazas Reversible",
                            Price = 31243m
                        },
                        new
                        {
                            ProductId = new Guid("c973afcb-7b99-420e-8187-dc7f761b53c6"),
                            Category = 3,
                            Description = "Cartera Cuero Genuino Reptil Bolso Mochila Mujer Cierre.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_869901-MLA54619063288_032023-F.webp",
                            Name = "Bolso de cuero genuino",
                            Price = 95000m
                        },
                        new
                        {
                            ProductId = new Guid("8250654d-da6c-4e18-80b0-ca85dec932ec"),
                            Category = 3,
                            Description = "Anteojos de sol polarizados Vulk Reporter en color sblk/s10.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_604456-MLA48170692330_112021-O.webp",
                            Name = "Lente De Sol Vulk",
                            Price = 64800m
                        },
                        new
                        {
                            ProductId = new Guid("faf39cc2-2c7e-42aa-b52a-96c71936b526"),
                            Category = 3,
                            Description = "Smartwatch Reloj Inteligente Dt N0.1 Dt3 Mate Doble Malla.",
                            Discount = 13,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_748519-MLA72356877039_102023-F.webp",
                            Name = "Reloj inteligente elegante",
                            Price = 75950m
                        },
                        new
                        {
                            ProductId = new Guid("45f00bf3-8a7b-4d0b-8a26-28a61aaeb59c"),
                            Category = 3,
                            Description = "Zapatillas Puma Caven 2.0 Blanca",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_994477-MLA74957384571_032024-O.webp",
                            Name = "Zapatillas deportivas de moda",
                            Price = 84999m
                        },
                        new
                        {
                            ProductId = new Guid("798a1105-e44e-4b8c-ae88-4b9df0c0592f"),
                            Category = 4,
                            Description = "Juego De Sabanas Queen 400hilos 100% Algodon.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829765-MLA73477087898_122023-O.webp",
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 85265m
                        },
                        new
                        {
                            ProductId = new Guid("7b714cd8-e52e-4e98-a51b-a19a1758f1fc"),
                            Category = 4,
                            Description = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814774-MLA73709732208_012024-O.webp",
                            Name = "Jarrón de cerámica artesanal",
                            Price = 27550m
                        },
                        new
                        {
                            ProductId = new Guid("3e0cafbc-6750-4e81-a0b6-e3737f97cddb"),
                            Category = 4,
                            Description = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_929599-MLA54852993202_042023-F.webp",
                            Name = "Lámpara de pie moderna",
                            Price = 85050m
                        },
                        new
                        {
                            ProductId = new Guid("a2b372cc-2457-463d-a968-4060cc9caba0"),
                            Category = 4,
                            Description = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 35983m
                        },
                        new
                        {
                            ProductId = new Guid("e9fb7c40-588e-42ea-92aa-0fd570ef25de"),
                            Category = 5,
                            Description = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 28,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Set de maquillaje profesional",
                            Price = 39528m
                        },
                        new
                        {
                            ProductId = new Guid("aa6d01b2-8a84-4cc1-aed5-ac41d689a670"),
                            Category = 5,
                            Description = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_870569-MLA74827280389_022024-O.webp",
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 36827m
                        },
                        new
                        {
                            ProductId = new Guid("68da8533-c425-4e3e-8a0f-87f1ba5794c2"),
                            Category = 5,
                            Description = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918096-MLA74134687068_012024-O.webp",
                            Name = "Serum facial rejuvenecedor",
                            Price = 18290m
                        },
                        new
                        {
                            ProductId = new Guid("ae9f275c-2af5-4d3c-a072-8938082eed5b"),
                            Category = 5,
                            Description = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 24,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_999356-MLU74959566341_032024-O.webp",
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 92369m
                        },
                        new
                        {
                            ProductId = new Guid("d32d73a8-4f6e-471f-875f-1b05e71d71e9"),
                            Category = 5,
                            Description = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 60,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_864195-MLU75358350003_032024-F.webp",
                            Name = "Kit de manicura y pedicura",
                            Price = 4799m
                        },
                        new
                        {
                            ProductId = new Guid("3ce4aab8-835b-4eed-9141-e7b135ab44a5"),
                            Category = 6,
                            Description = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_819576-MLU75591901591_042024-F.webp",
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 283226m
                        },
                        new
                        {
                            ProductId = new Guid("e6dc21d6-5d34-4246-87c0-31f7101fb40c"),
                            Category = 6,
                            Description = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_853020-MLU74646955786_022024-F.webp",
                            Name = "Tienda de campaña para 4 personas",
                            Price = 150000m
                        },
                        new
                        {
                            ProductId = new Guid("6190334e-fb56-4403-a4f9-9d23981f556b"),
                            Category = 6,
                            Description = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_674284-MLU74132469460_012024-F.webp",
                            Name = "Raquetas de tenis de alta gama",
                            Price = 246900m
                        },
                        new
                        {
                            ProductId = new Guid("4ab8a007-595c-44e5-b3b6-9c5c63fd04ae"),
                            Category = 6,
                            Description = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_981675-MLU75436946294_042024-O.webp",
                            Name = "Balón de fútbol oficial",
                            Price = 62200m
                        },
                        new
                        {
                            ProductId = new Guid("cde5fd6c-9ce5-4029-b9d0-48965c1ef1f8"),
                            Category = 7,
                            Description = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_688616-MLA70719693003_072023-O.webp",
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 59900m
                        },
                        new
                        {
                            ProductId = new Guid("6a4f86a1-d3b0-41bf-bc23-717d00a7a23f"),
                            Category = 7,
                            Description = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_825422-MLA48732174078_012022-O.webp",
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 47491m
                        },
                        new
                        {
                            ProductId = new Guid("b653e94a-e9f2-4cb8-95aa-5cbf71eed639"),
                            Category = 7,
                            Description = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_681463-MLU72607866767_102023-O.webp",
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 29989m
                        },
                        new
                        {
                            ProductId = new Guid("87a6abab-4575-429d-8301-e7053e2eae27"),
                            Category = 7,
                            Description = "Juego de mesa estratégico con tablero plegable y fichas de madera.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_818301-MLU72732448659_112023-O.webp",
                            Name = "Juego de mesa de Ajedrez",
                            Price = 34400m
                        },
                        new
                        {
                            ProductId = new Guid("cdd1b483-338c-46e3-823c-81307792bd7d"),
                            Category = 8,
                            Description = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_756320-MLU70634026054_072023-F.webp",
                            Name = "Caja de vinos seleccionados",
                            Price = 187800m
                        },
                        new
                        {
                            ProductId = new Guid("33b4fc6c-f9b7-4038-ba05-25a54c06dc86"),
                            Category = 8,
                            Description = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 17,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_890748-MLA73914321216_012024-O.webp",
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 29682m
                        },
                        new
                        {
                            ProductId = new Guid("8730ede2-0e2b-445e-b26e-09f532b691f1"),
                            Category = 8,
                            Description = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745130-MLA51091920365_082022-O.webp",
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 4360m
                        },
                        new
                        {
                            ProductId = new Guid("d29d7d1e-1b2b-43d6-bf23-a8ac57c02112"),
                            Category = 8,
                            Description = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_773299-MLU72576428368_112023-O.webp",
                            Name = "Cafetera espresso automática",
                            Price = 241590m
                        },
                        new
                        {
                            ProductId = new Guid("3e6c6a49-fcab-49db-87e8-8a1f9bd1cbd6"),
                            Category = 9,
                            Description = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_737839-MLA52392671527_112022-O.webp",
                            Name = "Bestseller del New York Times",
                            Price = 15822m
                        },
                        new
                        {
                            ProductId = new Guid("ec549bc2-4a53-48cb-8f4c-103fdaea0fb1"),
                            Category = 9,
                            Description = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_869243-MLU74994926858_032024-O.webp",
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 17000m
                        },
                        new
                        {
                            ProductId = new Guid("2aa3918f-cfd7-4d49-9b80-340956b6ee47"),
                            Category = 9,
                            Description = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_789389-MLA42259351508_062020-O.webp",
                            Name = "Atlas geográfico interactivo",
                            Price = 16980m
                        },
                        new
                        {
                            ProductId = new Guid("bd8980ec-7d2e-49e9-bdbd-de96965bc641"),
                            Category = 9,
                            Description = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_924058-MLA50987231299_082022-F.webp",
                            Name = "Kit de experimentos científicos para niños",
                            Price = 27900m
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCardId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "category")
                        .WithMany("Product")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", "ProductName")
                        .WithMany("product")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", "SaleName")
                        .WithMany("SaleProduct")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductName");

                    b.Navigation("SaleName");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
