// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionVentas.Contexto;

namespace SistemaGestionVentas.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("67ba7298-586d-4b44-b01e-f6be54eafe83"),
                            CategoryId = 1,
                            Descripcion = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 0,
                            Name = "Lavadora de carga frontal",
                            Price = 8999m,
                            Url = "https://www.ejemplo.com/lavadora-de-carga-frontal"
                        },
                        new
                        {
                            ProductId = new Guid("fea71356-a6ce-4ce7-b549-2dfc7208c96e"),
                            CategoryId = 1,
                            Descripcion = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 50,
                            Name = "Licuadora de alta potencia",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/licuadora-de-alta-potencia"
                        },
                        new
                        {
                            ProductId = new Guid("0c5c4f44-eea7-4396-978e-06b18fc2157f"),
                            CategoryId = 1,
                            Descripcion = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 100,
                            Name = "Horno eléctrico de convección",
                            Price = 3999m,
                            Url = "https://www.ejemplo.com/horno-electrico-de-conveccion"
                        },
                        new
                        {
                            ProductId = new Guid("705c788f-b400-4c3a-bc3b-f9123689ae86"),
                            CategoryId = 1,
                            Descripcion = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 0,
                            Name = "Aspiradora robotizada",
                            Price = 2999m,
                            Url = "https://www.ejemplo.com/aspiradora-robotizada"
                        },
                        new
                        {
                            ProductId = new Guid("96aad6f6-8bfb-4689-8150-b4d464b2e883"),
                            CategoryId = 2,
                            Descripcion = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 20,
                            Name = "Smartphone de última generación",
                            Price = 12999m,
                            Url = "https://www.ejemplo.com/smartphone-de-ultima-generacion"
                        },
                        new
                        {
                            ProductId = new Guid("e3c71253-a6b0-4df5-9113-3b52df052ca0"),
                            CategoryId = 2,
                            Descripcion = "Portátil ultraligero con procesador XXX y memoria RAM de XXGB.",
                            Discount = 200,
                            Name = "Portátil ultraligero",
                            Price = 8999m,
                            Url = "https://www.ejemplo.com/portatil-ultraligero"
                        },
                        new
                        {
                            ProductId = new Guid("9c316c8b-c249-40a7-a511-caaee1d5001d"),
                            CategoryId = 2,
                            Descripcion = "Cámara digital réflex con sensor de XXMP y grabación de video en XXX.",
                            Discount = 0,
                            Name = "Cámara digital réflex",
                            Price = 4999m,
                            Url = "https://www.ejemplo.com/camara-digital-reflex"
                        },
                        new
                        {
                            ProductId = new Guid("a3ec467e-0912-4997-b47b-13dc98583179"),
                            CategoryId = 2,
                            Descripcion = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 70,
                            Name = "Smart TV de 55 pulgadas",
                            Price = 18999m,
                            Url = "https://www.ejemplo.com/smart-tv-de-55-pulgadas"
                        },
                        new
                        {
                            ProductId = new Guid("e9e9869d-48df-4fe7-a05f-585edfc535a5"),
                            CategoryId = 2,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 2499m,
                            Url = "https://www.ejemplo.com/auriculares-inalambricos"
                        },
                        new
                        {
                            ProductId = new Guid("4b82a44a-1123-4ef5-91d2-222971fd363e"),
                            CategoryId = 2,
                            Descripcion = "Consola de videojuegos de nueva generación con procesador XXX y gráficos de alta calidad.",
                            Discount = 1500,
                            Name = "Consola de videojuegos de nueva generación",
                            Price = 21999m,
                            Url = "https://www.ejemplo.com/consola-de-videojuegos"
                        },
                        new
                        {
                            ProductId = new Guid("7e3321cb-5648-462e-9d19-5b2200128238"),
                            CategoryId = 3,
                            Descripcion = "Abrigo de invierno acolchado con capucha y bolsillos con cierre.",
                            Discount = 0,
                            Name = "Abrigo de invierno acolchado",
                            Price = 3999m,
                            Url = "https://www.ejemplo.com/abrigo-de-invierno-acolchado"
                        },
                        new
                        {
                            ProductId = new Guid("16f6745e-1bc7-4b52-b696-eb8513e20ad2"),
                            CategoryId = 3,
                            Descripcion = "Bolso de cuero genuino con compartimentos interiores y correa ajustable.",
                            Discount = 0,
                            Name = "Bolso de cuero genuino",
                            Price = 2999m,
                            Url = "https://www.ejemplo.com/bolso-de-cuero-genuino"
                        },
                        new
                        {
                            ProductId = new Guid("f6eea3e0-64de-4223-8436-def8e0dcfd26"),
                            CategoryId = 3,
                            Descripcion = "Gafas de sol de diseño con montura de metal y lentes polarizadas.",
                            Discount = 100,
                            Name = "Gafas de sol de diseño",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/gafas-de-sol-de-diseno"
                        },
                        new
                        {
                            ProductId = new Guid("1bd67f66-98ec-4fd5-89fc-010a453b4a6a"),
                            CategoryId = 3,
                            Descripcion = "Reloj inteligente elegante con pantalla táctil y seguimiento de actividad.",
                            Discount = 0,
                            Name = "Reloj inteligente elegante",
                            Price = 2499m,
                            Url = "https://www.ejemplo.com/reloj-inteligente-elegante"
                        },
                        new
                        {
                            ProductId = new Guid("615c84fb-86a3-4afa-8afe-3cfb6d8e0ea3"),
                            CategoryId = 3,
                            Descripcion = "Zapatillas deportivas de moda con suela de goma antideslizante y diseño ergonómico.",
                            Discount = 150,
                            Name = "Zapatillas deportivas de moda",
                            Price = 1999m,
                            Url = "https://www.ejemplo.com/zapatillas-deportivas-de-moda"
                        },
                        new
                        {
                            ProductId = new Guid("d18df0b0-5e4a-41fc-b9f4-c99dd5a27e5c"),
                            CategoryId = 4,
                            Descripcion = "Juego de sábanas de algodón egipcio con funda de almohada y sábana bajera.",
                            Discount = 0,
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 1599m,
                            Url = "https://www.ejemplo.com/juego-de-sabanas-de-algodon-egipcio"
                        },
                        new
                        {
                            ProductId = new Guid("da4a5e4e-cbec-4525-85e0-53626123a6fe"),
                            CategoryId = 4,
                            Descripcion = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            Name = "Jarrón de cerámica artesanal",
                            Price = 899m,
                            Url = "https://www.ejemplo.com/jarron-de-ceramica-artesanal"
                        },
                        new
                        {
                            ProductId = new Guid("0a1c6348-c2e3-4bb7-9b3a-86af2e0a1831"),
                            CategoryId = 4,
                            Descripcion = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 8,
                            Name = "Lámpara de pie moderna",
                            Price = 2999m,
                            Url = "https://www.ejemplo.com/lampara-de-pie-moderna"
                        },
                        new
                        {
                            ProductId = new Guid("471cab60-4cfd-4d0e-aff6-e067ed06d451"),
                            CategoryId = 4,
                            Descripcion = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 100,
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 2499m,
                            Url = "https://www.ejemplo.com/juego-de-cuchillos-de-cocina"
                        },
                        new
                        {
                            ProductId = new Guid("bff20e49-83a8-47ea-becb-8fe42c011ad1"),
                            CategoryId = 5,
                            Descripcion = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 0,
                            Name = "Set de maquillaje profesional",
                            Price = 1999m,
                            Url = "https://www.ejemplo.com/set-de-maquillaje-profesional"
                        },
                        new
                        {
                            ProductId = new Guid("91db14be-94a3-48e8-a184-d023ce51ab27"),
                            CategoryId = 5,
                            Descripcion = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 100,
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/maquina-de-afeitar-electrica"
                        },
                        new
                        {
                            ProductId = new Guid("181b3b36-e800-44c4-b468-f65554deb83d"),
                            CategoryId = 5,
                            Descripcion = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            Name = "Serum facial rejuvenecedor",
                            Price = 799m,
                            Url = "https://www.ejemplo.com/serum-facial-rejuvenecedor"
                        },
                        new
                        {
                            ProductId = new Guid("cb8571c1-2fe7-4aff-a34f-3b2d86a856d0"),
                            CategoryId = 5,
                            Descripcion = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 50,
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 699m,
                            Url = "https://www.ejemplo.com/cepillo-de-dientes-electrico"
                        },
                        new
                        {
                            ProductId = new Guid("45342839-5d97-4a9f-8835-b30468fe5b81"),
                            CategoryId = 5,
                            Descripcion = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 0,
                            Name = "Kit de manicura y pedicura",
                            Price = 499m,
                            Url = "https://www.ejemplo.com/kit-de-manicura-y-pedicura"
                        },
                        new
                        {
                            ProductId = new Guid("c53f1139-3408-4423-997b-2ad0a9b71b64"),
                            CategoryId = 6,
                            Descripcion = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 0,
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 6999m,
                            Url = "https://www.ejemplo.com/bicicleta-de-montana"
                        },
                        new
                        {
                            ProductId = new Guid("827e4de1-c500-44d6-a32f-094f3a848f8d"),
                            CategoryId = 6,
                            Descripcion = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 60,
                            Name = "Tienda de campaña para 4 personas",
                            Price = 1999m,
                            Url = "https://www.ejemplo.com/tienda-de-campana"
                        },
                        new
                        {
                            ProductId = new Guid("573b83db-ec27-4694-893c-fc22a24a3cb6"),
                            CategoryId = 6,
                            Descripcion = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            Name = "Raquetas de tenis de alta gama",
                            Price = 2999m,
                            Url = "https://www.ejemplo.com/raquetas-de-tenis"
                        },
                        new
                        {
                            ProductId = new Guid("2dd7682b-f6b6-4d68-9355-b5e72dafafd8"),
                            CategoryId = 6,
                            Descripcion = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 50,
                            Name = "Balón de fútbol oficial",
                            Price = 799m,
                            Url = "https://www.ejemplo.com/balon-de-futbol-oficial"
                        },
                        new
                        {
                            ProductId = new Guid("9152d0f4-a8ec-4737-9e72-0a70fbc9dfbd"),
                            CategoryId = 7,
                            Descripcion = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 40,
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/set-de-construccion-de-lego"
                        },
                        new
                        {
                            ProductId = new Guid("9b0c5347-966e-4b44-8cc9-71e8a80e493a"),
                            CategoryId = 7,
                            Descripcion = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 1999m,
                            Url = "https://www.ejemplo.com/muneca-interactiva"
                        },
                        new
                        {
                            ProductId = new Guid("e88130af-1a8e-40f6-8633-e8c96bd78c28"),
                            CategoryId = 7,
                            Descripcion = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 50,
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 999m,
                            Url = "https://www.ejemplo.com/rompecabezas-de-1000-piezas"
                        },
                        new
                        {
                            ProductId = new Guid("76e793ce-1a9d-4cba-8cd9-195db89cc06c"),
                            CategoryId = 7,
                            Descripcion = "Juego de mesa estratégico con tablero plegable y fichas numeradas.",
                            Discount = 0,
                            Name = "Juego de mesa estratégico",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/juego-de-mesa-estrategico"
                        },
                        new
                        {
                            ProductId = new Guid("eee12635-5f72-402e-bd78-6281bc7cdcf7"),
                            CategoryId = 8,
                            Descripcion = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            Name = "Caja de vinos seleccionados",
                            Price = 2999m,
                            Url = "https://www.ejemplo.com/caja-de-vinos-seleccionados"
                        },
                        new
                        {
                            ProductId = new Guid("a4182d21-ba9b-4ef3-9755-95eac5bd0e7c"),
                            CategoryId = 8,
                            Descripcion = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 20,
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 799m,
                            Url = "https://www.ejemplo.com/cesta-de-frutas-frescas"
                        },
                        new
                        {
                            ProductId = new Guid("4f3d8527-adf4-42d8-8f03-ebde390cdc0b"),
                            CategoryId = 8,
                            Descripcion = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 1499m,
                            Url = "https://www.ejemplo.com/set-de-chocolates-belgas"
                        },
                        new
                        {
                            ProductId = new Guid("731a2ea3-bd8a-48de-8130-55b0d56858a2"),
                            CategoryId = 8,
                            Descripcion = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 10,
                            Name = "Cafetera espresso automática",
                            Price = 3999m,
                            Url = "https://www.ejemplo.com/cafetera-espresso-automatica"
                        },
                        new
                        {
                            ProductId = new Guid("59907b68-cdd4-4f71-af6d-a947481d8f8d"),
                            CategoryId = 9,
                            Descripcion = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            Name = "Bestseller del New York Times",
                            Price = 599m,
                            Url = "https://www.ejemplo.com/bestseller-del-new-york-times"
                        },
                        new
                        {
                            ProductId = new Guid("9279d841-9222-46b2-be71-bc95944dce92"),
                            CategoryId = 9,
                            Descripcion = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 1999m,
                            Url = "https://www.ejemplo.com/coleccion-de-clasicos-literarios"
                        },
                        new
                        {
                            ProductId = new Guid("fc8c8d04-5cae-41ac-8428-7a91b2be0352"),
                            CategoryId = 9,
                            Descripcion = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            Name = "Atlas geográfico interactivo",
                            Price = 999m,
                            Url = "https://www.ejemplo.com/atlas-geografico-interactivo"
                        },
                        new
                        {
                            ProductId = new Guid("a8c48524-c08a-4863-bf00-eb7e69611ea0"),
                            CategoryId = 9,
                            Descripcion = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 90,
                            Name = "Kit de experimentos científicos para niños",
                            Price = 799m,
                            Url = "https://www.ejemplo.com/kit-de-experimentos-cientificos"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProducts");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", null)
                        .WithMany("product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", null)
                        .WithMany("SaleProducts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
