// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionVentas.Contexto;

namespace Aplicacion.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240418023407_migra")]
    partial class migra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("29f94189-f059-454a-9bf0-a4f4410094f7"),
                            CategoryId = 1,
                            Descripcion = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_818355-MLU74163648935_012024-F.webp",
                            Name = "Lavadora de carga frontal",
                            Price = 579999m
                        },
                        new
                        {
                            ProductId = new Guid("561ceb17-81a5-4ee2-8380-1f186128ecdd"),
                            CategoryId = 1,
                            Descripcion = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 61,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745773-MLA47575105862_092021-O.webp",
                            Name = "Licuadora de alta potencia",
                            Price = 42500m
                        },
                        new
                        {
                            ProductId = new Guid("bfa8b8be-ae45-4cb4-bbe7-9c0efeaf805b"),
                            CategoryId = 1,
                            Descripcion = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700777-MLU75436781292_042024-O.webp",
                            Name = "Horno eléctrico de convección",
                            Price = 169999m
                        },
                        new
                        {
                            ProductId = new Guid("952765eb-1c5a-487e-a60b-181e742c6c6d"),
                            CategoryId = 1,
                            Descripcion = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 43,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678901-MLU75358482641_032024-O.webp",
                            Name = "Aspiradora robotizada",
                            Price = 70705m
                        },
                        new
                        {
                            ProductId = new Guid("45b897b1-2120-4056-b1a1-7c33dbad9b79"),
                            CategoryId = 2,
                            Descripcion = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816025-MLU72748491987_112023-O.webp",
                            Name = "Smartphone de última generación",
                            Price = 1900000m
                        },
                        new
                        {
                            ProductId = new Guid("08dbd388-3c71-4637-a628-ba666ea61fb1"),
                            CategoryId = 2,
                            Descripcion = "Inflador De Neumáticos Portátil X8",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_667807-MLU72649504918_112023-O.webp",
                            Name = "Inflador Portátil ultraligero",
                            Price = 400000m
                        },
                        new
                        {
                            ProductId = new Guid("68408c62-18fd-4726-918e-c5ac951948dc"),
                            CategoryId = 2,
                            Descripcion = "Camara Digital Mirrorless Sony Alpha A6100 4k Wifi Sel1650.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_659460-MLU72646998907_112023-O.webp",
                            Name = "Cámara digital réflex Sony",
                            Price = 1069000m
                        },
                        new
                        {
                            ProductId = new Guid("32a3de0d-8847-452a-ae8a-0e8749e124cd"),
                            CategoryId = 2,
                            Descripcion = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_796079-MLU75556122361_042024-F.webp",
                            Name = "Smart TV de 55 pulgadas",
                            Price = 734999m
                        },
                        new
                        {
                            ProductId = new Guid("2f8c0398-1214-4440-8a65-8da6f7da3352"),
                            CategoryId = 2,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_938092-MLA45480677826_042021-O.webp",
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("5ae5bfa7-78d6-47ef-bbc4-42a7288bcd17"),
                            CategoryId = 2,
                            Descripcion = "Sony PlayStation 5 825GB God of War Ragnarok Bundle color blanco y negro.",
                            Discount = 11,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700033-MLA69689802995_052023-O.webp",
                            Name = "Sony Playstation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("42087386-c097-430d-b151-f8aa89e45fcb"),
                            CategoryId = 3,
                            Descripcion = "Acolchado edredón 2 plazas y 1/2 (2 plazas y media) liso reversible Abrigado invierno.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_748192-MLA53582903699_022023-O.webp",
                            Name = "Acolchados Lisos 2 1/2 Plazas Reversible",
                            Price = 31243m
                        },
                        new
                        {
                            ProductId = new Guid("7af2c6a7-e6e0-4d22-a32e-eeaddfcc267a"),
                            CategoryId = 3,
                            Descripcion = "Cartera Cuero Genuino Reptil Bolso Mochila Mujer Cierre.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_869901-MLA54619063288_032023-F.webp",
                            Name = "Bolso de cuero genuino",
                            Price = 95000m
                        },
                        new
                        {
                            ProductId = new Guid("bdb312da-59f8-407a-82ea-e50be13fc4a4"),
                            CategoryId = 3,
                            Descripcion = "Anteojos de sol polarizados Vulk Reporter en color sblk/s10.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_604456-MLA48170692330_112021-O.webp",
                            Name = "Lente De Sol Vulk",
                            Price = 64800m
                        },
                        new
                        {
                            ProductId = new Guid("7f33e887-3ad6-4174-8d9e-68331fef34c1"),
                            CategoryId = 3,
                            Descripcion = "Smartwatch Reloj Inteligente Dt N0.1 Dt3 Mate Doble Malla.",
                            Discount = 13,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_748519-MLA72356877039_102023-F.webp",
                            Name = "Reloj inteligente elegante",
                            Price = 75950m
                        },
                        new
                        {
                            ProductId = new Guid("8c33fcbe-ca6c-4fd9-a145-908fd889a0b5"),
                            CategoryId = 3,
                            Descripcion = "Zapatillas Puma Caven 2.0 Blanca",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_994477-MLA74957384571_032024-O.webp",
                            Name = "Zapatillas deportivas de moda",
                            Price = 84999m
                        },
                        new
                        {
                            ProductId = new Guid("a9f2643a-4ce8-402a-96b1-e3153899a3bd"),
                            CategoryId = 4,
                            Descripcion = "Juego De Sabanas Queen 400hilos 100% Algodon.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829765-MLA73477087898_122023-O.webp",
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 85265m
                        },
                        new
                        {
                            ProductId = new Guid("f4ebb123-a7c2-49fc-93f4-43e09d68dc37"),
                            CategoryId = 4,
                            Descripcion = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814774-MLA73709732208_012024-O.webp",
                            Name = "Jarrón de cerámica artesanal",
                            Price = 27550m
                        },
                        new
                        {
                            ProductId = new Guid("46b0ab0d-b3a2-4881-a56a-7f6af27638f6"),
                            CategoryId = 4,
                            Descripcion = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_929599-MLA54852993202_042023-F.webp",
                            Name = "Lámpara de pie moderna",
                            Price = 85050m
                        },
                        new
                        {
                            ProductId = new Guid("ebde990a-d05e-450f-9b89-df9114965f74"),
                            CategoryId = 4,
                            Descripcion = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 35983m
                        },
                        new
                        {
                            ProductId = new Guid("8fda0834-4f1c-4e23-a3ca-7fc3f9c25827"),
                            CategoryId = 5,
                            Descripcion = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 28,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Set de maquillaje profesional",
                            Price = 39528m
                        },
                        new
                        {
                            ProductId = new Guid("34464048-0f32-4572-9ce3-2e11cece1cfe"),
                            CategoryId = 5,
                            Descripcion = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_870569-MLA74827280389_022024-O.webp",
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 36827m
                        },
                        new
                        {
                            ProductId = new Guid("f80660c9-1bb0-48f4-ad77-65971d02963f"),
                            CategoryId = 5,
                            Descripcion = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918096-MLA74134687068_012024-O.webp",
                            Name = "Serum facial rejuvenecedor",
                            Price = 18290m
                        },
                        new
                        {
                            ProductId = new Guid("8512eebe-7703-4b26-8f56-cb531647bd2e"),
                            CategoryId = 5,
                            Descripcion = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 24,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_999356-MLU74959566341_032024-O.webp",
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 92369m
                        },
                        new
                        {
                            ProductId = new Guid("0cf56d2e-faa7-4f4d-8ce5-476967e165d2"),
                            CategoryId = 5,
                            Descripcion = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 60,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_864195-MLU75358350003_032024-F.webp",
                            Name = "Kit de manicura y pedicura",
                            Price = 4799m
                        },
                        new
                        {
                            ProductId = new Guid("d0da5f05-8916-4e57-b0b5-5def8d0b39b5"),
                            CategoryId = 6,
                            Descripcion = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_819576-MLU75591901591_042024-F.webp",
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 283226m
                        },
                        new
                        {
                            ProductId = new Guid("7bc2be2f-dd0b-4e23-8e71-10934a1bc2b8"),
                            CategoryId = 6,
                            Descripcion = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_853020-MLU74646955786_022024-F.webp",
                            Name = "Tienda de campaña para 4 personas",
                            Price = 150000m
                        },
                        new
                        {
                            ProductId = new Guid("38b68a00-e8bd-46a6-a0e9-de44df0f4735"),
                            CategoryId = 6,
                            Descripcion = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_674284-MLU74132469460_012024-F.webp",
                            Name = "Raquetas de tenis de alta gama",
                            Price = 246900m
                        },
                        new
                        {
                            ProductId = new Guid("02b0b5a1-4761-426c-8509-9d83d44f69ab"),
                            CategoryId = 6,
                            Descripcion = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_981675-MLU75436946294_042024-O.webp",
                            Name = "Balón de fútbol oficial",
                            Price = 62200m
                        },
                        new
                        {
                            ProductId = new Guid("1bd91115-266f-46aa-82aa-9e47cb74ee82"),
                            CategoryId = 7,
                            Descripcion = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_688616-MLA70719693003_072023-O.webp",
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 59900m
                        },
                        new
                        {
                            ProductId = new Guid("3dfb6722-5ca7-413d-92a0-ed5e792511f8"),
                            CategoryId = 7,
                            Descripcion = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_825422-MLA48732174078_012022-O.webp",
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 47491m
                        },
                        new
                        {
                            ProductId = new Guid("8bf5b3d5-7164-4042-9b20-d4ea01a8f18f"),
                            CategoryId = 7,
                            Descripcion = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_681463-MLU72607866767_102023-O.webp",
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 29989m
                        },
                        new
                        {
                            ProductId = new Guid("d1feb028-a5f3-409d-8be7-d9cc35723985"),
                            CategoryId = 7,
                            Descripcion = "Juego de mesa estratégico con tablero plegable y fichas de madera.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_818301-MLU72732448659_112023-O.webp",
                            Name = "Juego de mesa de Ajedrez",
                            Price = 34400m
                        },
                        new
                        {
                            ProductId = new Guid("b61ca699-1cba-417c-ba2b-1af3ebdbccf6"),
                            CategoryId = 8,
                            Descripcion = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_756320-MLU70634026054_072023-F.webp",
                            Name = "Caja de vinos seleccionados",
                            Price = 187800m
                        },
                        new
                        {
                            ProductId = new Guid("9ac2cea9-81f1-4015-a11d-c6a53a05ff84"),
                            CategoryId = 8,
                            Descripcion = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 17,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_890748-MLA73914321216_012024-O.webp",
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 29682m
                        },
                        new
                        {
                            ProductId = new Guid("3838de78-e8a3-424b-98ce-7eac9f9f80ac"),
                            CategoryId = 8,
                            Descripcion = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745130-MLA51091920365_082022-O.webp",
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 4360m
                        },
                        new
                        {
                            ProductId = new Guid("91cde0d5-9990-4b91-acc0-354a80db106e"),
                            CategoryId = 8,
                            Descripcion = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_773299-MLU72576428368_112023-O.webp",
                            Name = "Cafetera espresso automática",
                            Price = 241590m
                        },
                        new
                        {
                            ProductId = new Guid("18b914f4-5177-4090-910c-7acf1900ff74"),
                            CategoryId = 9,
                            Descripcion = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_737839-MLA52392671527_112022-O.webp",
                            Name = "Bestseller del New York Times",
                            Price = 15822m
                        },
                        new
                        {
                            ProductId = new Guid("5fad3be9-e114-4e91-8ce0-12dcaafe5513"),
                            CategoryId = 9,
                            Descripcion = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_869243-MLU74994926858_032024-O.webp",
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 17000m
                        },
                        new
                        {
                            ProductId = new Guid("560d8764-7055-4433-90f3-6291ebd173ee"),
                            CategoryId = 9,
                            Descripcion = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_789389-MLA42259351508_062020-O.webp",
                            Name = "Atlas geográfico interactivo",
                            Price = 16980m
                        },
                        new
                        {
                            ProductId = new Guid("d5ac628d-d666-4cd4-a885-3aec5b117ff5"),
                            CategoryId = 9,
                            Descripcion = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_924058-MLA50987231299_082022-F.webp",
                            Name = "Kit de experimentos científicos para niños",
                            Price = 27900m
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", null)
                        .WithMany("product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", "Sale")
                        .WithMany("SaleProduct")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
