// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionVentas.Contexto;

namespace Aplicacion.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("ee95bf81-25db-4ad7-9896-87734628318c"),
                            CategoryId = 1,
                            Descripcion = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_818355-MLU74163648935_012024-F.webp",
                            Name = "Lavadora de carga frontal",
                            Price = 579999m
                        },
                        new
                        {
                            ProductId = new Guid("dc27eb9a-8ff4-4417-bbdf-9da805030158"),
                            CategoryId = 1,
                            Descripcion = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 61,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745773-MLA47575105862_092021-O.webp",
                            Name = "Licuadora de alta potencia",
                            Price = 42500m
                        },
                        new
                        {
                            ProductId = new Guid("a4cd6443-fd58-4e72-85e4-8b949c0d5632"),
                            CategoryId = 1,
                            Descripcion = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700777-MLU75436781292_042024-O.webp",
                            Name = "Horno eléctrico de convección",
                            Price = 169999m
                        },
                        new
                        {
                            ProductId = new Guid("89141ddc-7b52-4b61-a506-06116a9a19df"),
                            CategoryId = 1,
                            Descripcion = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 43,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678901-MLU75358482641_032024-O.webp",
                            Name = "Aspiradora robotizada",
                            Price = 70705m
                        },
                        new
                        {
                            ProductId = new Guid("1c82243f-1515-44a8-bb00-126356b7c33d"),
                            CategoryId = 2,
                            Descripcion = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816025-MLU72748491987_112023-O.webp",
                            Name = "Smartphone de última generación",
                            Price = 1900000m
                        },
                        new
                        {
                            ProductId = new Guid("c0459735-00b5-42e8-82f8-c152bc18267a"),
                            CategoryId = 2,
                            Descripcion = "Inflador De Neumáticos Portátil X8",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_667807-MLU72649504918_112023-O.webp",
                            Name = "Inflador Portátil ultraligero",
                            Price = 400000m
                        },
                        new
                        {
                            ProductId = new Guid("8fe8a9b0-fcdc-41ea-86f4-cb6a40111c8f"),
                            CategoryId = 2,
                            Descripcion = "Camara Digital Mirrorless Sony Alpha A6100 4k Wifi Sel1650.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_659460-MLU72646998907_112023-O.webp",
                            Name = "Cámara digital réflex Sony",
                            Price = 1069000m
                        },
                        new
                        {
                            ProductId = new Guid("149007c9-c929-46f7-8d96-e428478c7dd9"),
                            CategoryId = 2,
                            Descripcion = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_796079-MLU75556122361_042024-F.webp",
                            Name = "Smart TV de 55 pulgadas",
                            Price = 734999m
                        },
                        new
                        {
                            ProductId = new Guid("f3ff2551-4fe4-491f-bd03-80386f901169"),
                            CategoryId = 2,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_938092-MLA45480677826_042021-O.webp",
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("3f1ad266-6e92-486a-94ed-5b7298e4b6b7"),
                            CategoryId = 2,
                            Descripcion = "Sony PlayStation 5 825GB God of War Ragnarok Bundle color blanco y negro.",
                            Discount = 11,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700033-MLA69689802995_052023-O.webp",
                            Name = "Sony Playstation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("8f07ebeb-34b2-4b5c-9cb1-e8a70d763703"),
                            CategoryId = 3,
                            Descripcion = "Acolchado edredón 2 plazas y 1/2 (2 plazas y media) liso reversible Abrigado invierno.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_748192-MLA53582903699_022023-O.webp",
                            Name = "Acolchados Lisos 2 1/2 Plazas Reversible",
                            Price = 31243m
                        },
                        new
                        {
                            ProductId = new Guid("73fb8c48-b1d5-46cb-a189-0ed93742de8d"),
                            CategoryId = 3,
                            Descripcion = "Cartera Cuero Genuino Reptil Bolso Mochila Mujer Cierre.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_869901-MLA54619063288_032023-F.webp",
                            Name = "Bolso de cuero genuino",
                            Price = 95000m
                        },
                        new
                        {
                            ProductId = new Guid("cb945498-8f0f-4bd7-9c41-86f2560b6bcd"),
                            CategoryId = 3,
                            Descripcion = "Anteojos de sol polarizados Vulk Reporter en color sblk/s10.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_604456-MLA48170692330_112021-O.webp",
                            Name = "Lente De Sol Vulk",
                            Price = 64800m
                        },
                        new
                        {
                            ProductId = new Guid("92e22039-4e36-4885-b501-017892cad354"),
                            CategoryId = 3,
                            Descripcion = "Smartwatch Reloj Inteligente Dt N0.1 Dt3 Mate Doble Malla.",
                            Discount = 13,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_748519-MLA72356877039_102023-F.webp",
                            Name = "Reloj inteligente elegante",
                            Price = 75950m
                        },
                        new
                        {
                            ProductId = new Guid("d70b5144-7020-45f4-b973-868162580773"),
                            CategoryId = 3,
                            Descripcion = "Zapatillas Puma Caven 2.0 Blanca",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_994477-MLA74957384571_032024-O.webp",
                            Name = "Zapatillas deportivas de moda",
                            Price = 84999m
                        },
                        new
                        {
                            ProductId = new Guid("2aef7a24-99e4-4484-ac11-1af23295eef5"),
                            CategoryId = 4,
                            Descripcion = "Juego De Sabanas Queen 400hilos 100% Algodon.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829765-MLA73477087898_122023-O.webp",
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 85265m
                        },
                        new
                        {
                            ProductId = new Guid("bbd83a7d-17ad-4f57-a4cc-44c94aa63a48"),
                            CategoryId = 4,
                            Descripcion = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814774-MLA73709732208_012024-O.webp",
                            Name = "Jarrón de cerámica artesanal",
                            Price = 27550m
                        },
                        new
                        {
                            ProductId = new Guid("d25f8def-9da1-4e7e-b9e9-b529d0f42ade"),
                            CategoryId = 4,
                            Descripcion = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_929599-MLA54852993202_042023-F.webp",
                            Name = "Lámpara de pie moderna",
                            Price = 85050m
                        },
                        new
                        {
                            ProductId = new Guid("d7f3a4ad-f41d-45b1-97c1-e51901ec3f45"),
                            CategoryId = 4,
                            Descripcion = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 35983m
                        },
                        new
                        {
                            ProductId = new Guid("071d1a12-bfd8-49f2-bb35-95eef198f7e3"),
                            CategoryId = 5,
                            Descripcion = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 28,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Set de maquillaje profesional",
                            Price = 39528m
                        },
                        new
                        {
                            ProductId = new Guid("fcc6e3ed-3f2f-4c53-a109-d3d207455cbd"),
                            CategoryId = 5,
                            Descripcion = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_870569-MLA74827280389_022024-O.webp",
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 36827m
                        },
                        new
                        {
                            ProductId = new Guid("6374796e-015d-4ca0-b149-543ecab3fab9"),
                            CategoryId = 5,
                            Descripcion = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918096-MLA74134687068_012024-O.webp",
                            Name = "Serum facial rejuvenecedor",
                            Price = 18290m
                        },
                        new
                        {
                            ProductId = new Guid("f9c0c674-84ab-42fb-8e7f-c7c64e624857"),
                            CategoryId = 5,
                            Descripcion = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 24,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_999356-MLU74959566341_032024-O.webp",
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 92369m
                        },
                        new
                        {
                            ProductId = new Guid("5d386339-d5a8-4673-a1a3-d31066844093"),
                            CategoryId = 5,
                            Descripcion = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 60,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_864195-MLU75358350003_032024-F.webp",
                            Name = "Kit de manicura y pedicura",
                            Price = 4799m
                        },
                        new
                        {
                            ProductId = new Guid("1766f2b1-75be-4103-bab3-efb0b3191c14"),
                            CategoryId = 6,
                            Descripcion = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_819576-MLU75591901591_042024-F.webp",
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 283226m
                        },
                        new
                        {
                            ProductId = new Guid("b07d5b1e-695a-401f-bba9-df00e8d525c2"),
                            CategoryId = 6,
                            Descripcion = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_853020-MLU74646955786_022024-F.webp",
                            Name = "Tienda de campaña para 4 personas",
                            Price = 150000m
                        },
                        new
                        {
                            ProductId = new Guid("c28ccc5f-5c4d-4453-8119-a9989e3e078f"),
                            CategoryId = 6,
                            Descripcion = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_674284-MLU74132469460_012024-F.webp",
                            Name = "Raquetas de tenis de alta gama",
                            Price = 246900m
                        },
                        new
                        {
                            ProductId = new Guid("2e645ead-656d-4ed0-8d4b-357277129ec3"),
                            CategoryId = 6,
                            Descripcion = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_981675-MLU75436946294_042024-O.webp",
                            Name = "Balón de fútbol oficial",
                            Price = 62200m
                        },
                        new
                        {
                            ProductId = new Guid("8ae75ae6-63d3-418c-9d3e-f1b632e21281"),
                            CategoryId = 7,
                            Descripcion = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_688616-MLA70719693003_072023-O.webp",
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 59900m
                        },
                        new
                        {
                            ProductId = new Guid("cea30e0b-5bab-4023-85c0-7f63be46f457"),
                            CategoryId = 7,
                            Descripcion = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_825422-MLA48732174078_012022-O.webp",
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 47491m
                        },
                        new
                        {
                            ProductId = new Guid("48630c2c-6936-4057-a0d3-d6ac00502f7b"),
                            CategoryId = 7,
                            Descripcion = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_681463-MLU72607866767_102023-O.webp",
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 29989m
                        },
                        new
                        {
                            ProductId = new Guid("c8fb4cc8-5ef0-4ac2-98b9-b3c76a1217f5"),
                            CategoryId = 7,
                            Descripcion = "Juego de mesa estratégico con tablero plegable y fichas de madera.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_818301-MLU72732448659_112023-O.webp",
                            Name = "Juego de mesa de Ajedrez",
                            Price = 34400m
                        },
                        new
                        {
                            ProductId = new Guid("582ba12d-3251-479a-8033-174606613b4b"),
                            CategoryId = 8,
                            Descripcion = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_756320-MLU70634026054_072023-F.webp",
                            Name = "Caja de vinos seleccionados",
                            Price = 187800m
                        },
                        new
                        {
                            ProductId = new Guid("b08b20d7-420b-4795-8033-e159a95ec1d0"),
                            CategoryId = 8,
                            Descripcion = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 17,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_890748-MLA73914321216_012024-O.webp",
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 29682m
                        },
                        new
                        {
                            ProductId = new Guid("60fe661f-c4a2-4c9b-aff4-9640bfcdf83a"),
                            CategoryId = 8,
                            Descripcion = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745130-MLA51091920365_082022-O.webp",
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 4360m
                        },
                        new
                        {
                            ProductId = new Guid("64161d03-8eb7-457a-a2b7-2dde19b05fae"),
                            CategoryId = 8,
                            Descripcion = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_773299-MLU72576428368_112023-O.webp",
                            Name = "Cafetera espresso automática",
                            Price = 241590m
                        },
                        new
                        {
                            ProductId = new Guid("3213612f-44cd-4858-8943-0ab15be56220"),
                            CategoryId = 9,
                            Descripcion = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_737839-MLA52392671527_112022-O.webp",
                            Name = "Bestseller del New York Times",
                            Price = 15822m
                        },
                        new
                        {
                            ProductId = new Guid("d495ee08-91f8-4293-9ecb-b7037bf18d79"),
                            CategoryId = 9,
                            Descripcion = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_869243-MLU74994926858_032024-O.webp",
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 17000m
                        },
                        new
                        {
                            ProductId = new Guid("7a7cc0a3-9ab7-4d32-9871-f878d897d422"),
                            CategoryId = 9,
                            Descripcion = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_789389-MLA42259351508_062020-O.webp",
                            Name = "Atlas geográfico interactivo",
                            Price = 16980m
                        },
                        new
                        {
                            ProductId = new Guid("ec796883-ce2e-4176-8343-764c0172c373"),
                            CategoryId = 9,
                            Descripcion = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_924058-MLA50987231299_082022-F.webp",
                            Name = "Kit de experimentos científicos para niños",
                            Price = 27900m
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", "Product")
                        .WithMany("product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", "Sale")
                        .WithMany("SaleProduct")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
