// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionVentas.Contexto;

#nullable disable

namespace Aplicacion.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("e957fdc1-0349-4b72-8227-02c16fb739b9"),
                            Category = 1,
                            Descripcion = "Lavadora de carga frontal con capacidad XX kg y múltiples programas de lavado.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_818355-MLU74163648935_012024-F.webp",
                            Name = "Lavadora de carga frontal",
                            Price = 579999m
                        },
                        new
                        {
                            ProductId = new Guid("8ed5af07-27bf-4c29-bd6d-7bf90d6034e1"),
                            Category = 1,
                            Descripcion = "Licuadora de alta potencia con motor de XXXW y cuchillas de acero inoxidable.",
                            Discount = 61,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745773-MLA47575105862_092021-O.webp",
                            Name = "Licuadora de alta potencia",
                            Price = 42500m
                        },
                        new
                        {
                            ProductId = new Guid("5c085131-ebfb-4f9e-b5bb-631e81341073"),
                            Category = 1,
                            Descripcion = "Horno eléctrico de convección con capacidad de XX litros y control digital.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700777-MLU75436781292_042024-O.webp",
                            Name = "Horno eléctrico de convección",
                            Price = 169999m
                        },
                        new
                        {
                            ProductId = new Guid("244d221d-5d89-4fd4-b23f-1af62b754a7c"),
                            Category = 1,
                            Descripcion = "Aspiradora robotizada con sistema de mapeo inteligente y succión potente.",
                            Discount = 43,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678901-MLU75358482641_032024-O.webp",
                            Name = "Aspiradora robotizada",
                            Price = 70705m
                        },
                        new
                        {
                            ProductId = new Guid("765fcf9c-6ac6-4efa-8411-206d8490fe5a"),
                            Category = 2,
                            Descripcion = "Smartphone de última generación con pantalla XX pulgadas y cámara de XXMP.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816025-MLU72748491987_112023-O.webp",
                            Name = "Smartphone de última generación",
                            Price = 1900000m
                        },
                        new
                        {
                            ProductId = new Guid("27d7ec7d-1127-45ed-a8b8-ecd182c2e827"),
                            Category = 2,
                            Descripcion = "Inflador De Neumáticos Portátil X8",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_667807-MLU72649504918_112023-O.webp",
                            Name = "Inflador Portátil ultraligero",
                            Price = 400000m
                        },
                        new
                        {
                            ProductId = new Guid("dbe2c41b-4f69-44e5-a030-9b1d85de53af"),
                            Category = 2,
                            Descripcion = "Camara Digital Mirrorless Sony Alpha A6100 4k Wifi Sel1650.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_659460-MLU72646998907_112023-O.webp",
                            Name = "Cámara digital réflex Sony",
                            Price = 1069000m
                        },
                        new
                        {
                            ProductId = new Guid("d01dd81d-e111-416b-b4ff-43809ab62bb1"),
                            Category = 2,
                            Descripcion = "Smart TV de 55 pulgadas con resolución 4K y sistema operativo XXX.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_796079-MLU75556122361_042024-F.webp",
                            Name = "Smart TV de 55 pulgadas",
                            Price = 734999m
                        },
                        new
                        {
                            ProductId = new Guid("738fff89-5871-473f-8125-fd50b6146084"),
                            Category = 2,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido y batería de larga duración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_938092-MLA45480677826_042021-O.webp",
                            Name = "Auriculares inalámbricos con cancelación de ruido",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("24d0c8c5-9158-4c52-aa40-4af237ac8864"),
                            Category = 2,
                            Descripcion = "Sony PlayStation 5 825GB God of War Ragnarok Bundle color blanco y negro.",
                            Discount = 11,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_700033-MLA69689802995_052023-O.webp",
                            Name = "Sony Playstation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("44fcbc6c-fbaf-498f-a0b2-ce6fe1d9c9a6"),
                            Category = 3,
                            Descripcion = "Acolchado edredón 2 plazas y 1/2 (2 plazas y media) liso reversible Abrigado invierno.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_748192-MLA53582903699_022023-O.webp",
                            Name = "Acolchados Lisos 2 1/2 Plazas Reversible",
                            Price = 31243m
                        },
                        new
                        {
                            ProductId = new Guid("451a370c-0c08-4d1e-8622-85f254608c28"),
                            Category = 3,
                            Descripcion = "Cartera Cuero Genuino Reptil Bolso Mochila Mujer Cierre.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_869901-MLA54619063288_032023-F.webp",
                            Name = "Bolso de cuero genuino",
                            Price = 95000m
                        },
                        new
                        {
                            ProductId = new Guid("58707f3d-2c84-4e77-b10b-dac2d4bc5104"),
                            Category = 3,
                            Descripcion = "Anteojos de sol polarizados Vulk Reporter en color sblk/s10.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_604456-MLA48170692330_112021-O.webp",
                            Name = "Lente De Sol Vulk",
                            Price = 64800m
                        },
                        new
                        {
                            ProductId = new Guid("a5cb40a8-d947-4a7a-9ff3-bfa134450499"),
                            Category = 3,
                            Descripcion = "Smartwatch Reloj Inteligente Dt N0.1 Dt3 Mate Doble Malla.",
                            Discount = 13,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_748519-MLA72356877039_102023-F.webp",
                            Name = "Reloj inteligente elegante",
                            Price = 75950m
                        },
                        new
                        {
                            ProductId = new Guid("c5314553-d220-46ab-ac3b-20455086816b"),
                            Category = 3,
                            Descripcion = "Zapatillas Puma Caven 2.0 Blanca",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_994477-MLA74957384571_032024-O.webp",
                            Name = "Zapatillas deportivas de moda",
                            Price = 84999m
                        },
                        new
                        {
                            ProductId = new Guid("b3b2aa62-5918-4302-b697-39311ca59c72"),
                            Category = 4,
                            Descripcion = "Juego De Sabanas Queen 400hilos 100% Algodon.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829765-MLA73477087898_122023-O.webp",
                            Name = "Juego de sábanas de algodón egipcio",
                            Price = 85265m
                        },
                        new
                        {
                            ProductId = new Guid("5a144705-8cdf-45ae-a1c4-e8741a870f98"),
                            Category = 4,
                            Descripcion = "Jarrón de cerámica artesanal con acabado brillante y diseño moderno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814774-MLA73709732208_012024-O.webp",
                            Name = "Jarrón de cerámica artesanal",
                            Price = 27550m
                        },
                        new
                        {
                            ProductId = new Guid("ae65a894-d527-49c7-bdd1-3d650486063a"),
                            Category = 4,
                            Descripcion = "Lámpara de pie moderna con base de acero inoxidable y pantalla ajustable.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_929599-MLA54852993202_042023-F.webp",
                            Name = "Lámpara de pie moderna",
                            Price = 85050m
                        },
                        new
                        {
                            ProductId = new Guid("7f3a5c62-e476-43ae-bd60-096b20097209"),
                            Category = 4,
                            Descripcion = "Juego de cuchillos de cocina de alta calidad con mango ergonómico y hoja de acero inoxidable.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Juego de cuchillos de cocina de alta calidad",
                            Price = 35983m
                        },
                        new
                        {
                            ProductId = new Guid("ec525cfe-1958-443f-a12f-2ade7619e048"),
                            Category = 5,
                            Descripcion = "Set de maquillaje profesional con paleta de sombras, labiales y brochas.",
                            Discount = 28,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910185-MLA50009263187_052022-O.webp",
                            Name = "Set de maquillaje profesional",
                            Price = 39528m
                        },
                        new
                        {
                            ProductId = new Guid("1faaa577-f24b-408d-981d-1da0455c55d1"),
                            Category = 5,
                            Descripcion = "Máquina de afeitar eléctrica de precisión con cabezales flotantes y recortador de precisión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_870569-MLA74827280389_022024-O.webp",
                            Name = "Máquina de afeitar eléctrica de precisión",
                            Price = 36827m
                        },
                        new
                        {
                            ProductId = new Guid("d25c8e4a-4685-472d-87cf-5601362a6a39"),
                            Category = 5,
                            Descripcion = "Serum facial rejuvenecedor con ácido hialurónico y vitaminas antioxidantes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918096-MLA74134687068_012024-O.webp",
                            Name = "Serum facial rejuvenecedor",
                            Price = 18290m
                        },
                        new
                        {
                            ProductId = new Guid("36b22fc7-a46a-461a-97c1-a70859f1baa3"),
                            Category = 5,
                            Descripcion = "Cepillo de dientes eléctrico recargable con temporizador y cabezales intercambiables.",
                            Discount = 24,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_999356-MLU74959566341_032024-O.webp",
                            Name = "Cepillo de dientes eléctrico recargable",
                            Price = 92369m
                        },
                        new
                        {
                            ProductId = new Guid("4f2fd766-bc40-4f7d-a04b-adb1dab9f266"),
                            Category = 5,
                            Descripcion = "Kit de manicura y pedicura con lima, cortaúñas y herramientas de precisión.",
                            Discount = 60,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_864195-MLU75358350003_032024-F.webp",
                            Name = "Kit de manicura y pedicura",
                            Price = 4799m
                        },
                        new
                        {
                            ProductId = new Guid("e257fac8-a105-4c70-bf9e-7acbca8a4eb0"),
                            Category = 6,
                            Descripcion = "Bicicleta de montaña todo terreno con cuadro de aluminio y cambios Shimano.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_819576-MLU75591901591_042024-F.webp",
                            Name = "Bicicleta de montaña todo terreno",
                            Price = 283226m
                        },
                        new
                        {
                            ProductId = new Guid("650c8256-88b9-493c-ad62-fb01899f57a9"),
                            Category = 6,
                            Descripcion = "Tienda de campaña para 4 personas con doble techo y sistema de ventilación.",
                            Discount = 25,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_853020-MLU74646955786_022024-F.webp",
                            Name = "Tienda de campaña para 4 personas",
                            Price = 150000m
                        },
                        new
                        {
                            ProductId = new Guid("017600de-c7da-41f8-9352-8511bf1a2aa7"),
                            Category = 6,
                            Descripcion = "Raquetas de tenis de alta gama con tecnología de absorción de impactos y empuñadura ergonómica.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_674284-MLU74132469460_012024-F.webp",
                            Name = "Raquetas de tenis de alta gama",
                            Price = 246900m
                        },
                        new
                        {
                            ProductId = new Guid("a4fef914-10c8-4e81-af6b-61db4a389b32"),
                            Category = 6,
                            Descripcion = "Balón de fútbol oficial con diseño aerodinámico y cubierta de cuero sintético.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_981675-MLU75436946294_042024-O.webp",
                            Name = "Balón de fútbol oficial",
                            Price = 62200m
                        },
                        new
                        {
                            ProductId = new Guid("42f84ce2-e29a-4990-a10e-028ee129f0b5"),
                            Category = 7,
                            Descripcion = "Set de construcción de bloques de LEGO con XX piezas y figuras coleccionables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_688616-MLA70719693003_072023-O.webp",
                            Name = "Set de construcción de bloques de LEGO",
                            Price = 59900m
                        },
                        new
                        {
                            ProductId = new Guid("37b29a1f-5229-4d8e-85dc-68d2229c5cc4"),
                            Category = 7,
                            Descripcion = "Muñeca interactiva con funciones inteligentes y accesorios intercambiables.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_825422-MLA48732174078_012022-O.webp",
                            Name = "Muñeca interactiva con funciones inteligentes",
                            Price = 47491m
                        },
                        new
                        {
                            ProductId = new Guid("960c7357-4cbf-46f3-801a-e35701abf028"),
                            Category = 7,
                            Descripcion = "Rompecabezas de 1000 piezas con imagen de paisaje panorámico.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_681463-MLU72607866767_102023-O.webp",
                            Name = "Rompecabezas de 1000 piezas",
                            Price = 29989m
                        },
                        new
                        {
                            ProductId = new Guid("84b318e5-0d67-4776-8e49-c57ad998142f"),
                            Category = 7,
                            Descripcion = "Juego de mesa estratégico con tablero plegable y fichas de madera.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_818301-MLU72732448659_112023-O.webp",
                            Name = "Juego de mesa de Ajedrez",
                            Price = 34400m
                        },
                        new
                        {
                            ProductId = new Guid("52d318f2-8534-4667-9fd6-b0324aadea74"),
                            Category = 8,
                            Descripcion = "Caja de vinos seleccionados con variedad de cepas y añejamiento mínimo de X años.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_756320-MLU70634026054_072023-F.webp",
                            Name = "Caja de vinos seleccionados",
                            Price = 187800m
                        },
                        new
                        {
                            ProductId = new Guid("b4c525ad-2210-4c0d-b2ae-4592dac56028"),
                            Category = 8,
                            Descripcion = "Cesta de frutas frescas de temporada con selección de frutas maduras y jugosas.",
                            Discount = 17,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_890748-MLA73914321216_012024-O.webp",
                            Name = "Cesta de frutas frescas de temporada",
                            Price = 29682m
                        },
                        new
                        {
                            ProductId = new Guid("fb9fd0c7-59e7-4b5e-92e4-759eaa2674df"),
                            Category = 8,
                            Descripcion = "Set de gourmet de chocolates belgas con variedad de sabores y presentación elegante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_745130-MLA51091920365_082022-O.webp",
                            Name = "Set de gourmet de chocolates belgas",
                            Price = 4360m
                        },
                        new
                        {
                            ProductId = new Guid("fd0ccd0a-393e-4a34-88b9-cb775b7a63b1"),
                            Category = 8,
                            Descripcion = "Cafetera espresso automática con sistema de preparación rápida y vaporizador integrado.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_773299-MLU72576428368_112023-O.webp",
                            Name = "Cafetera espresso automática",
                            Price = 241590m
                        },
                        new
                        {
                            ProductId = new Guid("4ead1861-83ad-4b11-b52b-de06a20990eb"),
                            Category = 9,
                            Descripcion = "Bestseller del New York Times en formato papel o digital.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_737839-MLA52392671527_112022-O.webp",
                            Name = "Bestseller del New York Times",
                            Price = 15822m
                        },
                        new
                        {
                            ProductId = new Guid("3184ccb6-58c1-4a80-b3f2-5e52ab489d14"),
                            Category = 9,
                            Descripcion = "Colección de clásicos de la literatura mundial en edición especial.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_869243-MLU74994926858_032024-O.webp",
                            Name = "Colección de clásicos de la literatura mundial",
                            Price = 17000m
                        },
                        new
                        {
                            ProductId = new Guid("1f018129-d4c4-4f60-9030-8db0d703eafa"),
                            Category = 9,
                            Descripcion = "Atlas geográfico interactivo con mapas detallados y funciones multimedia.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_789389-MLA42259351508_062020-O.webp",
                            Name = "Atlas geográfico interactivo",
                            Price = 16980m
                        },
                        new
                        {
                            ProductId = new Guid("c768cbab-fe30-4654-9914-4e4aaaf14011"),
                            Category = 9,
                            Descripcion = "Kit de experimentos científicos para niños con materiales seguros y guía de actividades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_924058-MLA50987231299_082022-F.webp",
                            Name = "Kit de experimentos científicos para niños",
                            Price = 27900m
                        });
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCardId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Category", "category")
                        .WithMany("Product")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.SaleProduct", b =>
                {
                    b.HasOne("SistemaGestionVentasTP1.Model.Product", "Product")
                        .WithMany("product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionVentasTP1.Model.Sale", "sale")
                        .WithMany("SaleProduct")
                        .HasForeignKey("SaleId");

                    b.Navigation("Product");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Product", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("SistemaGestionVentasTP1.Model.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
